#!/bin/bash

worklog=$HOME/bin/data/worklog


function printwork {
    IFS=$'\n'
    clear
    myecho -bo "=======the work log message======="
    for line in `cat $worklog`
    do
        if [ ${line:0:2} == '--' ]
        then
            myecho -bo "----------------------${line:2}-------------------------"
        else
            echo $line
        fi
    done
}

function addwork {
myecho -r "-----------------------daily work-------------------------"
PS3='Choose the project: '

# 8 words for each project name For better Formatting when print
select project in "6.0     " "77315.1 " "t8 5.1  " "jiaotu  " "pike 5.1" "tshark3 " "other   "
do
    echo $project
    break
done


#myecho -bo "Add the Work Log For Project $project:"

#read working
working=`zenity --entry --text "Add the Work Log For Project"`

if [ $? == 0 ]
then
    echo "save the worklog"
else
    myecho -r "Cancel Save the Worklog"
    exit
fi

dd=`date +%U`
let "dd=$dd+1"

formated_date="`date +%G`.${dd}.`date +%w`"
formated_week="`date +%G`.${dd}"

date_working="$formated_date     $project       $working"

IFS=$'\n'


#read the last week info first

for line in `cat $worklog`
do
    if [ ${line:0:2} == '--' ]
    then
        last_week=${line:2}
    fi
done

if [ "$last_week" != "$formated_week" ]
then
    echo "--$formated_week" >>$worklog
fi

echo $date_working>>$worklog

printwork

}





###############

if [ $# == 0 ]
then
    printwork
else
    addwork
fi
