#! /bin/bash

black='\E[30m'
red='\E[31m'
green='\E[32m'
yellow='\E[33m'
blue='\E[34m'
magenta='\E[35m'
cyan='\E[36m'
white='\E[37m'
bold='\033[1m'


function cecho()
{
    para=$1
    case ""$1"" in

        "r" | "-r")
            begin=$red
            ;;

        "g" | "-g")
            begin=$green
            ;;

        "y" | "-y")
            begin=$yellow
            ;;

        "b" | "-b")
            begin=$blue
            ;;

        "m" | "-m")
            begin=$magenta
            ;;

        "c" | "-c")
            begin=$cyan
            ;;

        "bo" | "-bo")
            begin=$bold
            ;;

    esac


    echo -en "$begin";
    shift
    echo "$@"
    tput sgr0
}

function cecho_noline()
{
    para=$1
    case ""$1"" in

        "r" | "-r")
            begin=$red
            ;;

        "g" | "-g")
            begin=$green
            ;;

        "y" | "-y")
            begin=$yellow
            ;;

        "b" | "-b")
            begin=$blue
            ;;

        "m" | "-m")
            begin=$magenta
            ;;

        "c" | "-c")
            begin=$cyan
            ;;

        "bo" | "-bo")
            begin=$bold
            ;;

    esac


    echo -en "$begin";
    shift
    echo -en "$@"
    echo -en $black
}


if [[ $# -lt 2 ]]
then
    echo -e "\033[1musage: myecho [color] message you want out put\033[0m"
    echo "color index:"
    echo -en "r\t"
    cecho r red
    echo -en "g\t"
    cecho g green
    echo -en "y\t"
    cecho y yellow
    echo -en "b\t"
    cecho b blue
    echo -en "m\t"
    cecho m magenta
    echo -en "c\t"
    cecho c cyan
    echo -en "bo\t"
    cecho bo bold
    cecho bo "-nolf means no line feed"
elif [[ $1 == "-nolf" ]]
then
    shift
    cecho_noline $@
else
    cecho $@
fi


dummy() {
    T='Text'
    echo -e "         --       40       41       42       43       44       45       46       47 "
    for FGs in '   0' '   1' '  30' '1;30' '  31' '1;31' '  32' '1;32' '  33' '1;33' '  34' '1;34' '  35' '1;35' '  36' '1;36' '  37' '1;37'
    do FG=${FGs// /}m 
        echo -en " $FGs \033[$FG  $T  "
        for BG in 40m 41m 42m 43m 44m 45m 46m 47m 
        do echo -en "$EINS \033[$FG\033[$BG  $T \033[0m\033[$BG \033[0m"
        done
        echo
    done
    echo -e "\033[0m"
}

