#!/bin/sh

ARGS="";
while [ "$#" -gt 0 ]; do
    ARGS=$ARGS" $1"
    shift 1
done

echo $ARGS


echo "abc" |od -b

start_time=$(date +"%s")
sleep 1
end_time=$(date +"%s")
timeuse=$(($end_time-$start_time))

hours=$(($timeuse / 3600))
mins=$((($timeuse %3600) / 60))
secs=$(($timeuse%60))

echo "sleep use $hours hours, $mins mins, $secs sec"

