#!/bin/bash

sudo adb wait-for-device root
sudo adb wait-for-device remount 
cur=`date +%m%d%H%M`
foldername="${cur}_$1"
echo $foldername
mkdir $foldername
cd $foldername
sudo adb pull /system/framework/services.jar . 
sudo adb pull /system/framework/framework.jar . 
sudo adb pull /system/framework/framework-res.apk . 
