#!/bin/bash
TOPFILE=build/core/envsetup.mk
FULLDIR=`pwd`
while [ `pwd` != / ]
do
	if [ -f $TOPFILE ]
	then
		ROOTDIR=`pwd`
		break
	fi
	cd ..
done


POS=${#ROOTDIR}

#compute the project name
cd ..
ROOTDIR=`pwd`

ROOTPOS=${#ROOTDIR}

PROJECT=${FULLDIR:$ROOTPOS+1:$POS-$ROOTPOS-1}

GITREPO=${FULLDIR:$POS+1}
echo "git push ssh://zhenjun.zhang@10.0.0.160:29418/platform/$GITREPO/ HEAD:refs/for/$PROJECT"

