#!/bin/bash
IFS=$'\n'
echo
for line in $(cat $HOME/bin/hint)
do
    if [[ ${line:0:2} == '--' ]]
    then
        echo
        myecho -bo "${line:2}"
    else
        myecho -g "$line"
    fi
done

echo
echo
