#!/bin/bash

command="repo init -c --no-tags -u gitadmin@10.5.2.49:android/platform/manifest.git -b"
#command="repo init -u gitadmin@gitmirror.spreadtrum.com:android/platform/manifest -b"
#repo init -u  gitadmin@gitmirror.spreadtrum.com:android/platform/manifest -b sprdroido_pdk

#compute last folder name
#aaa=`pwd`
#bbb=`cd .. && pwd &`
#lst_folder_name=${aaa#${bbb}/}

lst_folder_name=`pwd|sed 's/.*\///'`

if [ $# -eq 0 ]
then
    echo "use the default folder name as branch ?"
    select ans in "Y" "N"
    do
        echo $ans
        if [ $ans == "Y" ]
        then
            echo xxxx
            $command $lst_folder_name
        fi
        break
    done
else
    $command $1
fi
myecho -y "repo sync -c --no-tags -j8"
