#!/bin/bash

killserver() {
    servername=`sudo adb shell ps|grep $1|awk -F " " '{print $2}'`
    echo $servername
    if [ ! $servername ]
    then
        servername=`sudo adb shell ps -ef|grep $1|awk -F " " '{print $2}'`
    fi
    sudo adb shell kill $servername
}

if [ $# == 0 ]
    then
        killserver system_server
    exit
fi

killserver $1
