#!/bin/bash
echo "enter the src and dst"
src=$1
dst=$2
linkforder=("frameworks/base/core" "frameworks/base/services" "frameworks/base/packages/SystemUI")
cd $dst
for a in ${linkforder[@]}
do
    parent_forder=${a%/*}
    mkdir -p $parent_forder
    echo $parent_forder
    ln -s $src/$a $dst/$parent_forder
done

