#!/bin/sh

sudo adb wait-for-device root
sleep 1
sudo adb wait-for-device remount
sleep 1
sudo adb push ~/bin/data/blacklist /data/local/tmp/blacklist
echo "push blacklist to /data/local/tmp/blacklist"
sleep 1

name=`date +%m_%d_%H-%M`
cd ~/logs/monkeylog/
mkdir $name
cd $name
#sudo adb logcat -c; sudo adb logcat -b events -b main -b system > ~/bugs/monkeylog/$name&
sudo adb logcat -v threadtime -b main > ~/logs/monkeylog/$name/main_log&
sudo adb logcat -v threadtime -b events > ~/logs/monkeylog/$name/event_log&
sudo adb logcat -v threadtime -b system> ~/logs/monkeylog/$name/system_log&

while true
do
sudo adb shell monkey --pct-appswitch 35 --pct-syskeys 10 --pct-majornav 0 --pct-touch 40 -s 48 --throttle 200 --ignore-crashes --ignore-timeouts --ignore-security-exceptions --pkg-blacklist-file /data/local/tmp/blacklist --kill-process-after-error -v -v -v 750000
sleep 10
done
