#! /bin/bash

function show_phone_book(){
    myecho bo my phone book
    echo
    cat $HOME/bin/_phonebook|sort -b
    echo
}

function add_phone_book(){
    myecho bo add phone number
    myecho -b "enter phone number"
    read phone_name
    myecho -b "enter name"
    read phone_number
    if [[ ${#phone_name} -lt 8 ]]
    then
        phone_name="$phone_name\t"
    fi
    echo -e "$phone_name\t\t$phone_number">>$HOME/bin/_phonebook
}

if [[ $# == 0 ]]
then
    show_phone_book
elif [[ $1 == "-add" ]]
then
    add_phone_book
    show_phone_book
else
    show_phone_book|grep $1
fi
