#!/bin/bash
if [[ $# -lt 1 ]]
then
    myecho -r "usage: mypush out/target/product/scxxx/system/lib/libmedia.so"
    exit
fi

lib=$1
echo $lib

so=`echo $lib |awk -F "system" '{print $2}'`
so="system$so"
echo $so


myecho -g "push $lib to $so"

sudo adb push $lib $so
