#!/bin/bash
function croot {
    local TOPFILE=build/envsetup.sh
    local FULLDIR=`pwd`
    while [ `pwd` != / ]
    do
        if [ -f $TOPFILE ]
        then
            local ROOTDIR=`pwd`
            break
        fi
        cd ..
    done
    if [ `pwd` == / ]
        then
        echo "Can not find Android Root Folder"
        return -1
    fi
}


function mam {
    if [ ! $ANDROID_PRODUCT_OUT ]
    then
        echo "You should initial the Android environment, before use this command!"
        return
    fi
    last_pwd=`pwd`
    mm 2>&1|tee ~/tmp/tmplog
    for result in `cat ~/tmp/tmplog |grep "Install:" |sed "s/.*Install://"`
    do
        croot
        mypush $result 
        if [ $? -ne 0 ]
        then
            myecho -r "!! Device is not connection !!!"
        fi
        cd $last_pwd
    done
}

function cds {
    croot
    cd frameworks/base/services
}

function cdc {
    croot
    cd frameworks/base/core
}

alias cdout='cd $ANDROID_PRODUCT_OUT'

function mypush()
{
    if [ $# -lt 1 ]
    then
        echo "usage: mypush out/target/product/scxxx/system/lib/libmedia.so"
        return
    fi

    #push services.jar or framework.jar or res.apk
    if [ "$1" == "s" ]
    then
        cd $ANDROID_PRODUCT_OUT
        adb push system/framework/services.jar /system/framework/
        croot
        return
    elif [ "$1" == "f" ]
    then
        cd $ANDROID_PRODUCT_OUT
        adb push system/framework/framework.jar /system/framework/
        croot
        return
    elif [ "$1" == "r" ]
    then
        cd $ANDROID_PRODUCT_OUT
        adb push system/framework/framework-res.apk /system/framework/
        croot
        return
    fi

    echo push..

    lib=$1
    havefolder=`echo $lib | grep "/"`

    if [ "$havefolder" != "" ]
    then
        so=`echo $lib |awk -F "system" '{print $2}'`
        so="system$so"
        echo $so

        myecho -g "push $lib to $so"

        sudo adb push $lib $so
    else
        backup=`pwd`
        cdout
        cd system
        libname=`find -name ${lib}*`
        pushtolibname=`echo $libname |sed "s/.//"`
        echo "adb push $libname system$pushtolibname"
        sudo adb push $libname system$pushtolibname
        cd $backup
    fi
}

