#!/bin/bash
function croot {
    local TOPFILE=build/envsetup.sh
    local FULLDIR=`pwd`
    while [ `pwd` != / ]
    do
        if [ -f $TOPFILE ]
        then
            local ROOTDIR=`pwd`
            break
        fi
        cd ..
    done
    if [ `pwd` == / ]
        then
        echo "Can not find Android Root Folder"
    fi
}


function mam {
    if [ ! $ANDROID_PRODUCT_OUT ]
    then
        echo "You should initial the Android environment, before use this command!"
        return
    fi
    last_pwd=`pwd`
    mm 2>&1|tee ~/tmp/tmplog
    for result in `cat ~/tmp/tmplog |grep "Install:" |awk -F " " '{print $2}'`
    do
        croot
        mypush $result 
        if [ $? -ne 0 ]
        then
            myecho -r "!! Device is not connection !!!"
        fi
        cd $last_pwd
    done
}

function cds {
    croot
    cd frameworks/base/services
}

function cdc {
    croot
    cd frameworks/base/core
}

alias cdout='cd $ANDROID_PRODUCT_OUT'

